option('build_man',
  type: 'boolean',
  value: true,
  description: 'Build and install manual pages')

option('extract_acl',
  type: 'boolean',
  value: false,
  description: 'Enable ACL extraction support')

option('extract_xattr',
  type: 'boolean',
  value: false,
  description: 'Enable xattr extraction support')

option('prefer_static_deps',
  type: 'boolean',
  value: false,
  description: 'Prefer static variants of external dependencies when available')
